name: Build and Publish Python Package

on:
  workflow_dispatch:

jobs:
  python-build-n-publish:
    name: Build and publish Python package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout code

      - name: Set up Python 3.13.1
        uses: actions/setup-python@v2
        with:
          python-version: 3.13.1

      - name: Install local modules
        run: |
          python -m pip install --upgrade pip
          pip install -e ./
          pip install flake8 wheel

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run the script for testing
        run: |
          python -m lu77U_SHA256.Main --help
          python -m lu77U_SHA256.Main -t "Hell0 W0rld!!! Th!s !s myself lu77_u" -d -a
          python -m lu77U_SHA256.Main --text_from_file ./Sample_Text -d -a

      - name: Build source distribution and wheel
        run: |
          python setup.py sdist bdist_wheel

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI__Custom_Package_Upload__API_Token }}
          repository_url: https://upload.pypi.org/legacy/